client_config_backend: settings
client_config:
client_id: {}
client_secret: {}
save_credentials: True
save_credentials_backend: credentials.json
save_credentials_file: credentials.jsonget_refresh_token: Trueoauth_scope:
- https://www.googleapis.com/auth/drive.file
